name: Ticketify CI-CD - Development

on: 
  push:
    branches: ['main']
    
  pull_request: 
    branches: ['main']
  
  workflow_dispatch: 

env:
  AZURE_WEBAPP_NAME: ticketifyne-dev
  DOTNET_VERSION: '9.0.x'
  BUILD_OUTPUT: './publish_output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        
      - name: Setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
          
      - name: Restore dependencies
        run: dotnet restore ./Ticketify.sln
        
      - name: Build
        run: dotnet build ./API/API.csproj --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ./Ticketify.sln --configuration Release --verbosity normal
        
      # clean the API output before publishing (avoid leftover test artifacts)
      - name: Clean API publish output
        run: rm -rf ${{env.BUILD_OUTPUT}}
        
      - name: Publish
        run: dotnet publish ./API/API.csproj -c Release -o ${{env.BUILD_OUTPUT}} --no-build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{env.BUILD_OUTPUT}}
         
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    environment:
      name: 'Development'
      url: ${{steps.deploy-to-azure-web-app.outputs.webapp-url}}
    
    steps:
      - name: checkout
        uses: actions/checkout@v5
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ${{env.BUILD_OUTPUT}}
      
      - name: Azure login
        uses: azure/login@v2
        with: 
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
      # below step will create azure resources - using main_dev.bicep file.
      - name: Deploy azure resources - using main_dev.bicep file
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az group create --name ticketifyne-dev-resgrp --location centralindia
            az deployment group create \
            --resource-group ticketifyne-dev-resgrp \
            --template-file .github/infra/templates/main_dev.bicep \
            --parameters webAppName=${{env.AZURE_WEBAPP_NAME}} \
            sqlAdminPassword=${{secrets.AZURE_SQL_PASSWORD}} 
      
      - name: Deploy to azure web app
        id: deploy-to-azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          package: ${{env.BUILD_OUTPUT}}